name: Practise Github Action
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: printname
        run: echo "Hi, Iam Ajit"
      - name: final Message
        run: echo "Last Message"
       
